#!/usr/bin/env python3

import check
import sys

usr_vars = {}

def readfile(filename):
    tmp = []
    data = []
    with open(filename, "r+", encoding='utf8') as f:
        tmp = f.readlines()
        for line in tmp:
            line = line.strip("\n")
            data.append([token for token in line.split(" ")])
        return data
    
if len(sys.argv) == 1:
    print("\033[3;36;40mKAssembly interpreter")
    print("\033[1;37;40muse -h flag for more info")
else:
    if sys.argv[1] == "-h":
        print("\033[0;32;40mread your kasm file with ./kasm {your-file}.kasm")
        print("\033[1;37;40mYou can see example programs in the examplePrograms/ folder\n")
        print("\033[0;37;40mlist of flags:")
        print("-v: display version")
        print("\033[1;31;40m-d: link to language documentation (not implemented)")
    elif sys.argv[1] == "-v":
        print("Kasm interpreter ver 0.1 by Kenneth Soares")
    else:
        # do some file reading stuff
        lines = readfile(sys.argv[1])

        # eval fuctions in stdlib 
        check.eval_lines(lines,usr_vars)
